бэкенд от команды technokek 2 курса технопарка
java-park-mail-ru/Technokek-02-2018 pull request #1
Opened 2018-03-07 22:02 UTC by vladbusov

2018-03-24 10:49 UTC, KSolovyev reviewed
user_api_files/avatars/file1.png - мусор

2018-03-24 10:49 UTC, KSolovyev commented on src/main/java/main/Main.java
> +    CommandLineRunner init(AvatarStorageService storageService) {
давайте уберем это в сам сервис по аннотацию  `@PostConstruct`

2018-04-04 20:26 UTC, KSolovyev requested changes

2018-04-04 20:26 UTC, KSolovyev commented on pom.xml
> +        <java.version>1.8</java.version>
нужно на 9 java переехать

2018-04-04 20:26 UTC, KSolovyev commented on src/main/java/main/controllers/AvatarUploadController.java
> +    @Autowired
с единственным конструктором можно без `@Autowired`

2018-04-04 20:26 UTC, KSolovyev commented on src/main/java/main/service/Validation.java
> +    public @Nullable Message checkId(Long id) {
что это?

2018-04-04 20:26 UTC, KSolovyev commented on src/main/java/main/service/avatars/AvatarStorageSystem.java
> +        final String filename = StringUtils.cleanPath(file.getOriginalFilename());
у одного пользователя не должно быть возможности перетереть аватарку другого пользователя

2018-04-08 14:02 UTC, KSolovyev commented
чеккер упал

2018-04-08 14:21 UTC, KSolovyev requested changes

2018-04-08 14:21 UTC, KSolovyev commented on checks.xml
> +<?xml version="1.0"?>
Кажется, это лишний файл

2018-04-08 14:21 UTC, KSolovyev commented on pom.xml
> +        <java.version>8</java.version>
java 9

2018-04-08 14:21 UTC, KSolovyev commented on pom.xml
> +            <name>Spring Milestones</name>
если используете релизную версию спринга, репозитории с milestone'ами можно убрать

2018-04-08 14:21 UTC, KSolovyev commented on src/main/java/main/config/CrosOriginRS.java
> +public class CrosOriginRS {
typo "Cross"

2018-04-08 14:21 UTC, KSolovyev commented on src/main/java/main/controllers/AvatarUploadController.java
> +        return AvatarControllerService.dropAvatar(avatar, avatarStorageService);
Это же получение аватарки по имени файла?
почему serveFile?
Почему метод называется dropAvatar?
из-за названий методов возникает куча вопросов и ни одного ответа. Поправьте именование

2018-04-08 14:21 UTC, KSolovyev commented on src/main/java/main/service/avatars/AvatarControllerService.java
> +        System.out.println("kekekeke");
![image](https://user-images.githubusercontent.com/4122313/38468535-2d8b1378-3b50-11e8-8a52-6d412f9189c2.png)

2018-04-08 14:21 UTC, KSolovyev commented on src/main/java/main/service/avatars/AvatarStorageSystem.java
> +            if (filename.contains("..")) {
а что на счет '~'?

2018-04-08 14:21 UTC, KSolovyev commented on src/main/java/main/service/avatars/AvatarStorageSystem.java
> +        System.out.println("тут");
![image](https://user-images.githubusercontent.com/4122313/38468552-983581ae-3b50-11e8-988c-db3c6b233fd6.png)

2018-04-08 14:21 UTC, KSolovyev commented on src/main/java/main/service/avatars/AvatarStorageSystem.java
> +        final String filename = StringUtils.cleanPath(curUser.getId() + file.getOriginalFilename());
пользователь с id = 1, сможет перезаписать аватарки всем пользователям, id который начинается на 1

2018-04-08 14:21 UTC, KSolovyev commented on src/main/java/main/service/avatars/AvatarStorageSystem.java
> +    public Stream<Path> getAllAvatars() {
зачем это кому-то может потребоваться?

2018-04-08 14:21 UTC, KSolovyev commented on src/main/resources/db/migration/V2__users_unique_emails.sql
> +CREATE TRIGGER scoreboard
нет, нет, нет. Только не триггер. Сделайте это на бизнес логике, пожалуйста

2018-04-18 17:57 UTC, closed without merging

2018-04-18 18:01 UTC, vladbusov commented
теперь pull reqest из dev , а не из master https://github.com/java-park-mail-ru/Technokek-02-2018/pull/5